### Use "conda env create -f environment.yml" to create the environment
name: pixelalpha
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.12.3
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.2.1
  - cycler=0.12.1
  - filelock=3.13.1
  - fonttools=4.52.4
  - frozendict=2.4.4
  - fsspec=2024.2.0
  - html5lib=1.1
  - idna=3.7
  - install=1.3.5
  - intel-openmp=2021.4.0
  - jinja2=3.1.3
  - joblib=1.4.2
  - kiwisolver=1.4.5
  - lxml=5.2.2
  - markupsafe=2.1.5
  - matplotlib=3.9.0
  - mkl=2021.4.0
  - mpmath=1.3.0
  - multitasking=0.0.11
  - networkx=3.2.1
  - numpy=1.26.4
  - packaging=24.0
  - pandas=2.2.2
  - peewee=3.17.5
  - pillow=10.2.0
  - pip=24.0
  - platformdirs=4.2.2
  - pyparsing=3.1.2
  - python-dateutil=2.9.0.post0
  - pytz=2024.1
  - requests=2.32.3
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - seaborn=0.13.2
  - setuptools=69.5.1
  - six=1.16.0
  - soupsieve=2.5
  - sympy=1.12
  - tbb=2021.11.0
  - threadpoolctl=3.5.0
  - torch=2.3.0
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - tqdm=4.66.4
  - typing-extensions=4.9.0
  - tzdata=2024.1
  - urllib3=2.2.1
  - webencodings=0.5.1
  - wheel=0.43.0
  - yfinance=0.2.40
  - pip:
      - torch==2.3.0+cu118
      - torchaudio==2.3.0+cu118
      - torchvision==0.18.0+cu118
